### ISSUE TITLE
Too cumbersome even with the current docker image

### ISSUE THREAD

**Issue by ItsNoted** [frysztak/orpington-news#74]
Needs a better compose stack for easier installation. No one will use this over other options otherwise.

**Comment by frysztak** [comment]
hey @ItsNoted - thanks for the comment. I think installation difficulty is on par with other self-hosted apps. which part do you find cumbersome? is it about `traefik` labels in `docker-compose.yml`? because if so, those are not mandatory (and now that I think about it, including them in the example is probably rather misleading)
